my_web_site_homepage:
    pattern:  /
    defaults: { _controller: MyWebSiteBundle:Page:index }
    requirements:
        _method:  GET|POST

my_web_site_login:
    pattern:  /login
    defaults: { _controller: MyWebSiteBundle:Page:login }
    requirements:
        _method:  GET

my_web_site_admin:
    pattern:  /admin
    defaults: { _controller: MyWebSiteBundle:Page:admin }
    requirements:
        _method:  GET



