security:


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    oscar:  { password: $2a$10$vuotNDTCKUkyCRFhe6sGSehkUzF3j3cd1EBRcYAL1tXaUWBdiTUMS, roles: [ 'ROLE_USER' ] }
                    admin:  { password: $2a$10$Kq6ds/nDY6eojTr4bEf62e41GytcffH1.Afq2nRQ7AnSQ/Omuxm22, roles: [ 'ROLE_ADMIN' ] }

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        login_firewall:
            pattern: ^/login$
            anonymous: ~
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: my_web_site_login
                check_path: login_check
                use_forward: true
                default_target_path: my_web_site_admin
                #always_use_default_target_path: true
                csrf_provider: form.csrf_provider
                #target_path_parameter: acme_security_admin
            logout:
                path:   /logout
                target: /

    access_control:
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin, roles: ROLE_ADMIN }
